### ISSUE TITLE
Choose technical stacks

### ISSUE THREAD

**Issue by dotrungkien** [dotrungkien/eth-code-base#1]
We need to choose technical stack and version for this project:
## Contract
- [x] Contract: Truffle
- [x] Contract Security: Mythyx
- [x] Connect: Web3js

## Frontend
- [x] Frontend: Reacjs
- [x] Component: Viết lại dựa trên Drizzle

## CI CD
- [x] CI/CD: Framgia CI

## Testing
- [x] Test framework: Mocha + Chai + Sinon + [openzeppelin-test-helpers](https://github.com/OpenZeppelin/openzeppelin-test-helpers)

## Project structure
- [x] One for All project repo

**Comment by tranchien2002** [comment]
> We need to choose technical stack and version for this project:
> 
> * [x]  Contract: Truffle
> * [x]  Contract Security: Mythyx
> * [x]  Connect: Web3js
> * [x]  Frontend: Reacjs
> * [ ]  Component: Drizzle
> * [x]  Frontend: Vuejs
> * [x]  CI/CD: Framgia CI
> * [ ]  CI/CD: Circle CI
> * [x]  Test framework: Mocha + Chai + Sinon
> * [ ]  Test framework: Jest
> * [x] Devops: Docker

**Comment by dotrungkien** [comment]
Theo như những gì đã resaerch tại https://github.com/dotrungkien/eth-code-base/issues/4, mình sẽ thống nhất vài điểm
- Sử dụng một repo, client sẽ được init bên trong truffle project
- chia gitignore ra làm 2, một cho truffle, một cho web
- sử dụng async/await
- solidity ver 0.5x
- web3js 1.0x
- trufle 5x

**Comment by vinhyenvodoi98** [comment]
có thể setup giống cái vue (có thể chọn các setup như css hay sass) khi tạo project không anh ví dụ như chọn mạng ethereum hay loom chọn frontend là reactjs hay vuejs chẳng hạn ạ
mà gần đây em thấy họ code react hooks em cũng chưa tìm hiểu về cái này

em thử cái truffle react thì họ dùng web3js 1.0.37beta khá ổn định chưa thấy lỗi gì ạ

**Comment by dotrungkien** [comment]
@vinhyenvodoi98 cái đó có em ạ, nhưng anh đang để ở version 2.0.0, xây dựng thêm một cái command line để cho người dùng lựa chọn công nghệ
phase 1.0.0 này mình cứ xây dựng cái base đơn giản đã
