### ISSUE TITLE
Research about other complete projects like truffle boxes

### ISSUE THREAD

**Issue by dotrungkien** [dotrungkien/eth-code-base#4]
target to research 
- [x] react https://www.trufflesuite.com/boxes/react
- [x] drizzle https://www.trufflesuite.com/boxes/drizzle
- [x] react box web3 todo https://www.trufflesuite.com/boxes/react-box-web3-todo
- [x] truffle next https://www.trufflesuite.com/boxes/truffle-next
- [x] truffle react dapp https://www.trufflesuite.com/boxes/truffle-react-dapp
- [x] truffle create react app https://www.trufflesuite.com/boxes/truffle-create-react-app
- [x] truffle react redux https://www.trufflesuite.com/boxes/truffle-react-redux

**Comment by dotrungkien** [comment]
# Truffle create react app  

[trufflesuite.com/boxes/truffle-create-react-app](trufflesuite.com/boxes/truffle-create-react-app)

- solidity ver 0.4.18 quá cũ ❌
- truffle global, nhưng theo note thì là 4.x, cũ nốt ❌
- test mặc định của truffle ❌
- mono repo, web-app inside truffle project 
- react ver 16.4.2 ❌
- ko có eslint, ko có ci ❌
- sử dụng `Promise` chứ ko dùng `async/await` ❌
- tách riêng .gitignore giữa truffle project & web-app project ✅
- Mơi chỉ update với các tương tác trong app, chưa có update interval ❌

**Comment by dotrungkien** [comment]
# React box

[https://www.trufflesuite.com/boxes/react](https://www.trufflesuite.com/boxes/react)

- solidity ver 0.5.0 ✅
- test mặc định truffle
- reactjs 16.6 
- mono repo, web-app inside truffle project
- tách riêng .gitignore giữa truffle project & web-app project
- sử dụng `async/await` ✅
- có cả getWeb3 cho modern dapp browser ✅
- Mơi chỉ update với các tương tác trong app, chưa có update interval ❌

**Comment by dotrungkien** [comment]
# Drizzle box 

[https://www.trufflesuite.com/boxes/drizzle](https://www.trufflesuite.com/boxes/drizzle)

- solidity ver `>=0.4.21 <0.6.0` ✅
- reactjs 16.7
- mono repo, web-app inside truffle project
- tách riêng .gitignore giữa truffle project & web-app project
- sử dụng drizzle & drizzle-react & drizzle-react-component, vẫn được update liên tục ✅
- Mơi chỉ update với các tương tác trong app, chưa có update interval ❌

**Comment by dotrungkien** [comment]
# react box web3 todo ❌
[https://www.trufflesuite.com/boxes/react-box-web3-todo](https://www.trufflesuite.com/boxes/react-box-web3-todo)

- solidity quá cũ ❌
- code quá cũ ❌

**Comment by dotrungkien** [comment]
# Truffle react dapp  ❌
[https://www.trufflesuite.com/boxes/truffle-react-dapp](https://www.trufflesuite.com/boxes/truffle-react-dapp)

- last update Feb 2018 ❌

**Comment by dotrungkien** [comment]
# Truffle react redux 
[https://www.trufflesuite.com/boxes/truffle-react-redux](https://www.trufflesuite.com/boxes/truffle-react-redux)

- solidity ver 0.4.23 ❌
- sử dụng drizzle & drizzle-react 
- react ver 16.6 
- sử dụng redux & redux-saga ✅
- sử dụng PropTypes ✅
- chưa có contract cụ thể, mới chỉ dừng lại ở mức init web3 ❌

**Comment by dotrungkien** [comment]
# Truffle next
[https://www.trufflesuite.com/boxes/truffle-next](https://www.trufflesuite.com/boxes/truffle-next)

- solidity 0.4.24 ❌
- Next - serverside rendering, chưa rõ có ưu điểm gì
- Mới chỉ update với các tương tác trong app, chưa có update interval ❌

**Comment by dotrungkien** [comment]
Hầu như các project đều thiếu những điều này:
- update interval
- viết test & security check
- không có CI check
- không có tài liệu deploy

**Comment by diennguyenduy** [comment]
## Uport: Identity management, digitally sign transactions and easy login to dapps. 
https://github.com/uport-project

## Truffle saga-foundation/vueport-box

- có thể lên solidity 0.5.x
- web3 1.0.x

- chưa config được mạng (default rinkeby testnet) 

## Truffle react-uport-box

- sử dụng redux 
- react 15.x
- web3 0.18.x
